stages:
  - test

Linter:
  stage: test
  script:
    - docker --version
    - docker-compose --version
    - docker run hello-world
    - npm --version
    - node -v
    - echo "Yes!!"
    - echo "pr_id is $CI_MERGE_REQUEST_SOURCE_PROJECT_ID"
    - echo "next is"
    - echo $CI_EXTERNAL_PULL_REQUEST_IID
  only:
    refs:
      - gitlab-ci
