stages:
  - test
  - test2

Linter:
  stage: test
  script:
    - docker --version
    - docker-compose --version
    - docker run hello-world
    - echo "pr_id is $CI_MERGE_REQUEST_SOURCE_PROJECT_ID"
    - echo "next is"
    - echo $CI_EXTERNAL_PULL_REQUEST_IID
    - echo "is github $CI_EXTERNAL_PULL_REQUEST_IID"
    - npm --version
    - node -v
    - echo "Yes!!"
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    - nvm install v14.15.1
    - nvm use v14.15.1
    - nvm alias default v14.15.1
    - npm --version
    - node -v
  only:
    refs:
      - gitlab-ci
    variables:
      - $CI_EXTERNAL_PULL_REQUEST_IID

Test:
 stage: test2
 script:
   - echo "yes2!!!"
 only:
   variables:
     - '$CI_EXTERNAL_PULL_REQUEST_IID == null'
