stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --ignore-scripts --cache .npm --prefer-offline

Linter:
  stage: test
  script:
    - echo "hello-world!"
  only:
    - gitlab-ci
  except:
    - merge_requests
