stages:
  - test

Linter:
  stage: test
  script:
    - docker --version
    - docker-compose --version
    - docker run hello-world
    - npm --version
    - node -v
  only:
    - gitlab-ci
  except:
    - merge_requests
