stages:
  - test

Linter:
  stage: test
  script:
    - docker --version
    - docker-compose --version
    - docker run hello-world
    - npm --version
    - node -v
    - echo "Yes!!"
  only:
    refs:
      - gitlab-ci
    variables:
      - $CI_MERGE_REQUEST_ID
