stages:
  - test

Linter:
  stage: test
  script:
    - docker --version
    - docker-compose --version
    - docker run hello-world
    - npm --version
    - node -v
    - echo "Yes!!"
  only:
    - merge_requests
