name: CI

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Unit Tests
      run: |
        npm run test:ci

    - name: Build
      run: |
        npm run build

    - name: Storybook
      run: |
        npm run build-storybook
