name: CI

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (please, check you dependencies)
      run: npm ci

    - name: Linter (please, run `npm run lint` locally before merge)
      run: |
        npm run lint:ci

    - name: Unit Tests (please, run `npm run test` locally before merge)
      run: |
        npm run test:ci

    - name: Build (please, run `npm run build` locally before merge)
      run: |
        npm run build

    - name: Storybook Build (please, run `npm run build-storybook` locally before merge)
      run: |
        npm run build-storybook
